// ATRIBUTOS DAS CLASSES
const atributos = {
  barbaro: {
    principal: 'constituicao',
    forca: 3,
    destreza: 2,
    constituicao: 3,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  clerigo: {
    principal: 'carisma',
    forca: 2,
    destreza: 1,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 2,
    carisma: 3,
  },
  druida: {
    principal: 'sabedoria',
    forca: 2,
    destreza: 2,
    constituicao: 3,
    inteligencia: 2,
    sabedoria: 3,
    carisma: 1,
  },
  guerreiro: {
    principal: 'forca',
    forca: 3,
    destreza: 2,
    constituicao: 3,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  monge: {
    principal: 'destreza',
    forca: 3,
    destreza: 3,
    constituicao: 2,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  paladino: {
    principal: 'forca',
    forca: 3,
    destreza: 2,
    constituicao: 2,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 3,
  },
  patrulheiro: {
    principal: 'constituicao',
    forca: 2,
    destreza: 3,
    constituicao: 3,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  ladino: {
    principal: 'destreza',
    forca: 2,
    destreza: 3,
    constituicao: 2,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 3,
  },
  feiticeiro: {
    principal: 'sabedoria',
    forca: 2,
    destreza: 2,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 3,
    carisma: 1,
  },
  bruxo: {
    principal: 'inteligencia',
    forca: 1,
    destreza: 2,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 3,
    carisma: 2,
  },
  mago: {
    principal: 'inteligencia',
    forca: 1,
    destreza: 2,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 2,
    carisma: 3,
  },
};

  export { atributos };